### ISSUE TITLE
Stability / usability issues

### ISSUE THREAD

**Issue by jonom** [unclecheese/silverstripe-kickassets#80]
This module is so flipping awesome! But, unfortunately it has a few issues that make it a bit too unstable for production use for me. Understand if you have no time or inclination to address any of these @unclecheese with SS4 just around the corner, but thought it might be worth singling out the major issues in case anyone does get a chance to invest some tune-up time in this great module.

**Priority issues (IMHO)**
* [ ] [Can't move files or folders](https://github.com/unclecheese/silverstripe-kickassets/issues/14)
* [ ] [Options in [+] menu disappear](https://github.com/unclecheese/silverstripe-kickassets/issues/73)
* [ ] [Delete option disappears](https://github.com/unclecheese/silverstripe-kickassets/issues/26)
* [ ] [Thumbnail generation causes error message](https://github.com/unclecheese/silverstripe-kickassets/issues/66)
* [ ] [Can't select files from search results which are not also shown in main pane](https://github.com/unclecheese/silverstripe-kickassets/issues/31)
* [ ] [Multi-select broken for Windows users](https://github.com/unclecheese/silverstripe-kickassets/issues/55)
* [ ] [WYSIWYG insert width not respected](https://github.com/unclecheese/silverstripe-kickassets/issues/45)
